meter/subscription_manager.cc
When talking to AlertServer letting it know about our lack of
on-instance alert support.
=> Fix typo in content type

meter/id.h
We cannot have exceptions in public headers. It fails to compile the
extension for nodejs
=> Do not throw exceptions

meter/id.h, meter/subscription_manager.cc
Reduces the memory usage needed when dealing with more than one batch of
metrics (10,000 by default) by eliminating the copies to the temporary
vectors used for batching. Now we just pass iterators to the beginning
and end of the range.
=> Do batching with iterators, not copies

CMakeLists.txt, meter/subscription_manager.cc, meter/subscription_manager.h, test/interpreter_test.cc, util/intern.cc, util/string_pool.cc, util/string_pool.h
Adds `atlas.client.strPoolSize` and `atlas.client.strPoolAlloc` to track
the number of strings and bytes handled by our string pool.
=> Add a couple of gauges to track string pool usage

CMakeLists.txt, meter/subscription_manager.cc, util/intern.cc, util/string_pool.cc, util/string_pool.h
We were relying on the linker honoring the order of the object files,
but it's not reliable. We found a problem when users were using the
static library generated. Switch to an 'Construct On First Use' idiom to
avoid relying on the initialization order.
=> Prevent the static initialization order fiasco

atlas_client.cc, atlas_client.h, main.cc, test/runtests.cc, util/logger.cc, util/logger.h
Allow users of the library to request a console logger with a certain
verbosity. (1 == debug, 2 == info, etc.)
=> Expose UseConsoleLogger

util/config.cc, util/config.h, util/config_manager.cc, util/file_watcher.h
Provide a mechanism to enable/disable the publishing of metrics and
doing subscription based work depending on whether a file is abset/present
on the filesystem.
=> Add ability to enable/disable atlas using a file

CMakeLists.txt, atlas_client.cc, atlas_client.h, meter/function_gauge.h, util/config_manager.cc, util/config_manager.h
Currently the library notifies alert-server that we don't support
on-instance alerts. This was somewhat appropriate when there would be
only one atlas-client on the machine. Either the java client or this
native client, but now we have more users (like a system-agent) that
is likely to be installed alongside a jvm app, using the java client.
This PR adds a new function that can be used by system agents to opt-out
of notifying the alert server of lack of on-instance alerts.
=> Set notify

atlas_client.cc, atlas_client.h
Deprecated global functions that are not in the atlas namespace. The
`extern "C"` versions are not particularly useful, since you need C++ to
use the library. The original intention was to provide a C interface,
but that is not available, and it would require significant effort to
do.
=> Move global functions to the atlas namespace

meter/subscription_registry.cc, util/config.cc, util/config_manager.cc, util/config_manager.h
This can make it easier to debug certain problems when the value of the
config object is different from the expected value.
=> Add value of notify to debug output of a config 

atlas_client.cc, atlas_client.h, bench/tags.cc, interpreter/multiple_results.cc, interpreter/query.cc, meter/bucket_functions.cc, meter/id.h, meter/manual_clock.h, meter/tag.h, test/percentile_dist_summary_test.cc, test/percentile_timer_test.cc, test/small_tag_map_test.cc, test/strings_test.cc, util/config_manager.cc, util/intern.h, util/small_tag_map.h, util/string_pool.cc, util/string_pool.h
A custom small hash map is significantly faster than
the standard unordered_map and map.
```
Run on (8 X 2700 MHz CPU s)
2017-11-15 13:58:14
-----------------------------------------------------------------
Benchmark                          Time           CPU Iterations
-----------------------------------------------------------------
BM_TagsUnorderedMap/2           1129 ns       1127 ns     586127
BM_TagsUnorderedMap/4           2313 ns       2306 ns     295021
BM_TagsUnorderedMap/8           4716 ns       4694 ns     144693
BM_TagsUnorderedMap/16          9258 ns       9177 ns      71353
BM_TagsUnorderedMap/32         18544 ns      18501 ns      38493
BM_TagsOrdered/2                 994 ns        992 ns     667595
BM_TagsOrdered/4                2022 ns       2017 ns     339996 …
```
=> Switch tags implementation to use a custom map

atlas_client.cc, atlas_client.h, resources/atlas-config-reference.json, util/config.cc, util/config.h, util/config_manager.cc, util/logger.cc, util/logger.h
Previously we were hardcoding the log size configuration to 8 x 1MB log
files, but some applications that handle millions of measurements want
to run to with verbose logs for debugging purposes, and need to tweak
the defaults to increase the values significantly.
=> Make number and size of log files configurable

test/small_tag_map_test.cc, util/intern.h, util/small_tag_map.cc, util/small_tag_map.h
Refactor `SmallTagMap` to remove the dependency on the logger
implementation from the public API.
As part of the refactor add a couple of tests, and some helper methods
to `StrRef` to make it easier to use.
=> Remove logger from SmallTagMap public API

meter/subscription_registry.cc, test/subscription_registry_test.cc, util/config.h
We were using a wrong constructor for `measurements_for_rule` that would
apply the same `shared_ptr` to measurements to each of the rules.
=> Fix error when using multiple publish-config rules

meter/subscription_manager.cc
We were not honoring the configuration setting to allow users to disable metrics
validation
=> Honor shouldValidate config setting

meter/validation.cc, util/intern.h, util/strings.h
Instead of instantiating strings for each key/value pair, use the
underlying `StrRef`s directly.
=> Validate using StrRefs

interpreter/keep_drop_tags.cc, interpreter/word.h, test/interpreter_test.cc, test/subscription_registry_test.cc
Usually the number of tags to be dropped will be very small and using a
simple vector of StrRefs will be faster.
Adds a default virtual destructor to the Word interface. clang-6 was
complaining about it.
=> Use a vector for drop-tags instead of a hashmap

meter/validation.cc, util/intern.h, util/small_tag_map.h
The original thought behind the name was whether the reference is
pointing to something, similar to scala `Option[T]`, but it's not clear
whether the name refers to that or the length of the underlying string.
Rename it to be explicit about what it's actually checking.
=> Rename StrRef empty to is_null for clarity reasons

.gitignore, atlas_client.cc, atlas_client.h, interpreter/context.h, interpreter/vocabulary.h, meter/clock.h, meter/distribution_summary.h, meter/gauge.h, meter/id.h, meter/long_task_timer.h, meter/measurement.h, meter/registry.h, meter/subscription.h, meter/timer.h, test/interpreter_test.cc, util/http.cc, util/memory.h, util/optional.h, util/small_tag_map.cc, util/strings.h
* Add virtual destructors to interfaces
* Get rid of the `types.h` hack and make sure we only define
`std::make_unique` if not running under C++14 or newer.
* Do not throw from a `noexcept` function. (That would just call
`terminate()`) - switch to `assert`
=> Fix warnings and clean up the code

atlas_client.cc, util/http.cc, util/http.h
* Use RAII for dealing with the easy handles, lists, and buffers.
* Add global init and shutdown methods, which are needed by curl
This fixes a memory leak in the conditional get implementation (not
freeing the headers).
=> HTTP clean up

CMakeLists.txt, meter/subscription_manager.cc, test/http_test.cc, util/http.cc, util/http.h
Instead of passing common options, like timeouts, to each of the calls
make the client takes the options in the constructor. This should allow
us to extend the options at a later time (when adding retries)
=> Http client takes options in the constructor

meter/percentile_buckets.cc, test/percentile_buckets_test.cc
No need to use our manual counting of leading zeroes
=> Use x86 intrinsics for counting leading zeroes

.gitignore, meter/subscription_manager.cc, resources/atlas-config-reference.json, test/http_test.cc, util/config.cc, util/config.h, util/config_manager.cc, util/gzip.cc, util/gzip.h, util/http.cc, util/http.h
This fixes #29 by adding a config option (default false) to specify
whether to send batches in parallel. We use the curl multi interface so
no extra threads are needed, but more memory will be used compared to
just sending one batch at a time.
=> Send batches in parallel (optionally)

.travis.yml, CMakeLists.txt, CMakeModules/CodeCoverage.cmake, README.md, run-build.sh
Fixes #37. Currently we're doing a matrix build compiling for both g++
and clang++ and doing code coverage on both (meaning both are debug
builds with no optimizations). A refinement would be to do
it on only one of them, and do a release build for the other to verify
that the tests pass with optimizations as well.
=> Add support for test coverage reporting

test/bucket_counter_test.cc, test/bucket_dist_summary_test.cc, test/bucket_timer_test.cc
Looking at the code coverage report we didn't have any tests for the
bucket meters.
=> Add test cases for Bucket* meters

CMakeLists.txt, run-build.sh
Sometimes CMAKE_BUILD_TYPE was reported as Debug and sometimes DEBUG.
Convert it now to lower-case for a string case-insensitive comparison.
In addition exit the build script with errors if there is any error
detected in the intermediate commands.
=> Fix build-type detection and exit build if errors

test/bucket_counter_test.cc, test/bucket_dist_summary_test.cc, test/bucket_timer_test.cc
Remove some excessively verbose log messages from some
tests
=> Remove noise from tests

CMakeLists.txt, atlas_client.cc, meter/subscription_manager.cc, run-build.sh, test/config_manager_test.cc, test/config_test.cc, test/http_test.cc, test/resources/config.json, test/subscription_registry_test.cc, test/subscriptions_manager_test.cc, util/config.cc, util/config.h, util/config_manager.cc, util/config_manager.h, util/file_watcher.h, util/http.h, util/logger.cc, util/logger.h, util/small_tag_map.h
Split the big `Config` class into smaller, easier to understand classes:
* `LogConfig` for configuring logs and settings for debugging.
* `EndpointConfig` for setting the URLs to hit for different services.
* `HttpConfig` for configuring our HTTP client, including things like
batch sizes, and parallel sending of metrics.
* `FeatureConfig` to configure which settings are enabled, and how they
should work.
Fixes #43
=> Simplify Configuration Management

meter/percentile_buckets.cc
Some CPUs do not have it, and we can simply use `__builtin_clzll` which
is always available using gcc, and on clang x86_64 which is our target
architecture.
=> Do not use lzcnt

atlas_client.cc, main.cc, meter/subscription_manager.cc, meter/subscription_manager.h, test/config_manager_test.cc, test/http_test.cc, test/small_tag_map_test.cc, test/subscriptions_manager_test.cc, util/config_manager.cc, util/config_manager.h, util/http.cc, util/logger.cc, util/logger.h
* Make sure there are not static initialization issues around logging
* Fixed locking around `Logger` and setting new logging config.
* Avoid using `thread.detach`. This was causing some memory corruption
at shutdown time because the detached threads would attempt to read/write
member variables after the constructor for the object finished.
* Switch from `thread::sleep` to `cond_var.wait_for` which makes it
possible to `join` the threads without having to wait for the `sleep` to
finish.
=> Fix threading issues

interpreter/interpreter.cc, meter/subscription_manager.cc, meter/validation.cc
This fixes the case where the atlas client is initialized and stopped in
less time than it should take us to send the first batch of metrics.
Oridinarily we want to sleep a few seconds so we start collecting
metrics near the beginning of the step, but if we sleep then we cannot
notice the fact the user has requested a shutdown. Switch to the
condition variable that was introduced for this purpose.
=> Do not sleep before sending first batch of metrics

util/config.cc, util/config_manager.cc
Previously the config was loaded asynchronously, now we force the config
to be loaded first before returning from the call to Start.
This prevents a race condition where other services could fetch config
values before the initial config is loaded, and therefore would get the
defaults.
=> Initialize config at startup

main.cc, test/http_test.cc, util/gzip.cc, util/gzip.h, util/http.cc
libcurl was not automatically decompressing the payload. Manually handle
the case where the payload is compressed.
Note that we are allocating a fixed size 10MB buffer as the
max payload we can handle. This should be sufficient for now, but in the
near future we should dynamically resize the buffer as we uncompress the
data coming from network. (Switching to manual calls to inflate)
=> Deal with compressed payload in HTTP GETs

interpreter/vocabulary.cc, test/interpreter_test.cc
We need to get a copy of the shared pointer before calling `.get()`,
otherwise the memory will be freed before we access it
=> Fix illegal memory access in InWord

main.cc, meter/subscription_registry.cc, test/http_test.cc
This should fix the flaky http tests. Since the requests vector is
modified by a different thread there is no visibility guarantee for the
tests to get the latest requests unless some synchronization primitives
enforce that. This PR introduces a mutex to achieve that.
=> Synchronize http-test requests

util/buffer.cc, util/buffer.h
The previous buffer code was meant only to be used with curl/gzip which
pass big blocks of memory and therefore keeping the number of
reallocations/copies small. It relied on this fact to reduce to a
minimum the memory footprint (capacity=size).
Since buffer is now a more publicly visible class, then it makes sense
to use a more general purpose data structure.
=> Use a vector as our buffer implementation

interpreter/tags_value.cc, interpreter/tags_value.h
Since it's a header only library it causes problems for users of this
library. Remove it from that tags_value.h header that gets used as part
of our public API
=> Remove dependency on fmt/ from public api

meter/atlas_registry.cc, meter/subscription_manager.cc
Add a couple of gauges so we can track the number of measurements
produced by the registered meters, plus the number reported after
applying the rollup policy
=> Track the number of measurements pre/post rollups

meter/atlas_registry.cc, meter/atlas_registry.h, meter/registry.h, test/atlas_registry_test.cc, test/bucket_counter_test.cc, test/bucket_dist_summary_test.cc, test/bucket_timer_test.cc, test/default_dist_summary_test.cc, test/default_max_gauge_test.cc, test/function_gauge_test.cc, test/http_test.cc, test/interval_counter_test.cc, test/monotonic_counter_test.cc, test/percentile_dist_summary_test.cc, test/percentile_timer_test.cc, test/test_registry.h
If there are no external references to expired meters, remove them from
the registry.
Fix test_registry so it takes a clock so it can be used by our super
class (needed for counters)
=> Remove expired meters from registry

meter/atlas_registry.cc, test/atlas_registry_test.cc
Fix a bug where we were holding a copy of the meters, and making them
not be able to be removed from the registry
=> Make sure meters expire after calling measurements

.travis.yml, CMakeLists.txt, run-build.sh
When using travis enable the address sanitizer for clang builds. This
means we run two builds:
* gcc with code coverage and debug flags
* clang with address sanitizer checks and release flags
This should help us catch a wide variety of bugs, at the cost of a minor slow
down when running tests. When compiling this library for actual usage
ASAN should not be enabled to prevent a general slow down.
=> Use address sanitizer on travis builds

meter/publisher.cc, meter/validation.cc, meter/validation.h, test/validation_test.cc
Adds a function that can be used by users to get a list of errors or
warnings that were generated when validation is performed on some Tags
(including the 'name' key as part of the tags).
This will be used by the node-client when running in a dev setting
=> Add user-friendly function for validation checks

meter/validation.cc, test/validation_test.cc
Include the name of the key for which there is no value, or the value if
the key is empty. Makes it easier to track the source of an error.
=> Improve validation error messages

resources/atlas-config-reference.json, test/config_test.cc, test/resources/config.json, util/config_manager.cc, util/config_manager.h
This was a hack that was in place to let our Netflix alert server know
that the client didn't support on-instance evaluation of alerts. This is
no longer needed.
=> Remove notifyAlertServer support

atlas_client.cc, main.cc, meter/atlas_registry.cc, meter/atlas_registry.h, meter/consolidation_registry.cc, meter/subscription_manager.cc, meter/subscription_manager.h, test/cons_registry_test.cc
Make sure the client sends any partial updates to the main publish path,
and to all subscriptions at shutdown
=> Fix flushing of metrics at shutdown

bench/code/parse_json.cc, meter/subscription_manager.cc, test/subscriptions_manager_test.cc
Fixed the benchmark which wasn't actually reading the files, and after
running it showed that the insitu version is around 12-13% faster. Use
this version for reduced mem allocations and the extra speed.
=> Use 'in situ' json parser for subscriptions

.travis.yml, 3rd-party/ska/bytell_hash_map.hpp, 3rd-party/ska/flat_hash_map.hpp, 3rd-party/ska/unordered_map.hpp, bench/code/tags.cc, interpreter/context.cc, interpreter/context.h, interpreter/expression.cc, interpreter/expression.h, interpreter/group_by.cc, interpreter/interpreter.cc, interpreter/keep_drop_tags.cc, interpreter/query.cc, interpreter/query.h, interpreter/tags_value.h, interpreter/vocabulary.cc, meter/atlas_registry.cc, meter/consolidation_registry.h, meter/default_long_task_timer.h, meter/long_task_timer.h, meter/validation.cc, run-build.sh, test/expression_test.cc, test/interpreter_test.cc, util/optional.h, util/small_tag_map.h, util/string_pool.h
Use a faster hash table (`ska::flat_hash_map`) and use `StrRef` instead
of `std::string` wherever possible. This avoids map lookups when
interning strings.
A quick benchmark shows about a 3x speed up when parsing and evaluating
thousands of expressions on 40k measurements.
The performance is still not good enough so a subsequent PR will explore
using a query index for that use case.
=> Performance improvements evaluating expressions

run-build.sh
Gets rid of:
```
./run-build.sh: line 19: [: =: unary operator expected
./run-build.sh: line 24: [: =: unary operator expected
```
=> fix bash warnings when CC is not set

test/interpreter_test.cc
Verify we have the same behavior as the backend. See
Netflix/spectator#589 for more context.
=> add test case for nested :in expr

interpreter/query.cc, interpreter/query.h, test/queries_test.cc, test/query_utils.h
Test the disjunctive normal form generated by different combinations of
queries. Caught a bug with handling `not` queries (missing `break`)
=> Tests for query dnf

create-lcov-report.sh
A typo was preventing it from getting removed
=> Remove test dir from code coverage report

interpreter/query.cc, interpreter/query.h, interpreter/query_index.h, test/collections_test.cc, test/queries_test.cc, test/query_idx_test.cc, test/query_utils.h, util/collections.h
Add a query index to help evaluating thousands of queries. We'll need to
evaluate the resource utilization and optimize it in a subsequent PR, as
well as integrate it in the subscription manager if we can get the overhead to a reasonable level.
=> Add Query Index

meter/subscription_manager.cc
To avoid sending metrics with duplicated timestamps advance the clock
to the next step for the main publishing pipeline
=> Advance the clock at shutdown 1-step

meter/consolidation_registry.cc, meter/consolidation_registry.h, meter/default_counter.h, meter/default_max_gauge.h, meter/stepnumber.h, meter/subscription_manager.cc, test/cons_registry_test.cc, test/steplong_test.cc
We need to honor the timestamps and use step numbers to properly
attribute updates to a given interval. This also means we can't just
clear the registry after taken the measurements since the step numbers
can have partial updates for the next step, so we need a way to properly
expire them.
=> Use step numbers for the consolidated registry

atlas_client.cc, meter/clock.h, meter/consolidation_registry.cc, meter/consolidation_registry.h, meter/subscription_manager.cc, meter/subscription_manager.h, test/atlas_registry_test.cc, test/bucket_counter_test.cc, test/bucket_dist_summary_test.cc, test/bucket_timer_test.cc, test/cons_registry_test.cc, test/default_counter_test.cc, test/default_dist_summary_test.cc, test/default_timer_test.cc, test/http_test.cc, test/interval_counter_test.cc, test/monotonic_counter_test.cc, test/percentile_dist_summary_test.cc, test/percentile_timer_test.cc, test/system_clock_test.cc, test/test_registry.h
Make the consolidated registry update its values based on the beginning
of the step instead of the end. And send values at the beginning of each
minute.
A simple test where we update a counter once per minute at each possible
second is added to ensure the basic expectation is met.
=> Use the beginning of the step for updates

meter/publisher.cc, test/http_test.cc, test/subscriptions_manager_test.cc
Previously we were just using the number of measurements present versus the
number of measurements sent, but that also included measurements that
were valid and were not sent, for example, gauges with NaN values.
=> Properly count the number of validation errors

util/strings.h
Newer versions of clang fail to build this project due to the use of
`not1`. Simply replace the function with a lambda, and also tweak the
`tolower` string function to avoid the raw loop.
=> Fix warnings for deprecated functions
